import React from 'react'
import CopyButton from './CopyButton.tsx'

export const commissionEndpoints = [
 ['GET','Discover endpoints','/api/commission','Return the Sales Commission endpoint catalog.'],
 ['GET','List commissions','/api/commission/commissions','List calculated commissions with pagination and staff, invoice, client and paid filters.'],
 ['GET','Get commission','/api/commission/commissions/:id','Retrieve one calculated commission.'],
 ['GET','List policies','/api/commission/policies','List commission policies.'], ['POST','Create policy','/api/commission/policies','Create a policy with date range, policy type and percentage or ladder settings.'],
 ['GET','Get policy','/api/commission/policies/:id','Retrieve one commission policy.'], ['PUT','Update policy','/api/commission/policies/:id','Update a commission policy.'], ['DELETE','Delete policy','/api/commission/policies/:id','Delete a commission policy.'],
 ['GET','List staff assignments','/api/commission/applicable-staff','List staff-to-policy assignments.'], ['POST','Create staff assignment','/api/commission/applicable-staff','Assign one or more staff members to a policy.'],
 ['GET','Get staff assignment','/api/commission/applicable-staff/:id','Retrieve a staff assignment.'], ['PUT','Update staff assignment','/api/commission/applicable-staff/:id','Update a staff assignment.'], ['DELETE','Delete staff assignment','/api/commission/applicable-staff/:id','Delete a staff assignment.'],
 ['GET','List client assignments','/api/commission/applicable-clients','List client-to-policy assignments.'], ['POST','Create client assignment','/api/commission/applicable-clients','Assign one or more clients to a policy.'],
 ['GET','Get client assignment','/api/commission/applicable-clients/:id','Retrieve a client assignment.'], ['PUT','Update client assignment','/api/commission/applicable-clients/:id','Update a client assignment.'], ['DELETE','Delete client assignment','/api/commission/applicable-clients/:id','Delete a client assignment.'],
 ['GET','List hierarchies','/api/commission/hierarchies','List salesperson/coordinator commission hierarchies.'], ['POST','Create hierarchy','/api/commission/hierarchies','Create a hierarchy using salesman, coordinator and percent.'],
 ['GET','Get hierarchy','/api/commission/hierarchies/:id','Retrieve a hierarchy.'], ['PUT','Update hierarchy','/api/commission/hierarchies/:id','Update a hierarchy.'], ['DELETE','Delete hierarchy','/api/commission/hierarchies/:id','Delete a hierarchy.'],
 ['GET','List sales-admin groups','/api/commission/salesadmin-groups','List sales-admin/customer-group mappings.'], ['POST','Create sales-admin group','/api/commission/salesadmin-groups','Create a sales-admin/customer-group mapping.'],
 ['GET','Get sales-admin group','/api/commission/salesadmin-groups/:id','Retrieve a mapping.'], ['PUT','Update sales-admin group','/api/commission/salesadmin-groups/:id','Update a mapping.'], ['DELETE','Delete sales-admin group','/api/commission/salesadmin-groups/:id','Delete a mapping.'],
 ['GET','List receipts','/api/commission/receipts','List commission receipts with pagination and filters.'], ['POST','Create receipt','/api/commission/receipts','Create a receipt and mark selected commissions as paid.'],
 ['GET','Get receipt','/api/commission/receipts/:id','Retrieve a receipt with commission details.'], ['PUT','Update receipt','/api/commission/receipts/:id','Update a receipt and synchronize paid commissions.'], ['DELETE','Delete receipt','/api/commission/receipts/:id','Delete a receipt.'],
 ['GET','Get receipt PDF','/api/commission/receipts/:id/pdf','Return the receipt PDF as Base64.'], ['POST','Email receipt','/api/commission/receipts/:id/email','Send a receipt message to one or more email addresses.'],
 ['GET','Get chart data','/api/commission/chart','Return yearly commission and paid-commission chart data.'], ['POST','Recalculate commissions','/api/commission/recalculate','Recalculate commissions for the supplied invoice_ids.'],
] as const

export const commissionAnchor=(method:string,title:string)=>`api-commission-${method.toLowerCase()}-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}`
function body(method:string,path:string){if(method==='POST'&&path.endsWith('/recalculate'))return'{"invoice_ids":[101,102]}';if(path.endsWith('/email'))return'{"sent_to":["sales@example.com"],"message":"Your commission receipt"}';if(path.endsWith('/receipts'))return'{"amount":250,"date":"2026-08-13","paymentmode":"1","list_commission":[10,11],"note":"August commissions"}';if(path.endsWith('/hierarchies'))return'{"salesman":7,"coordinator":3,"percent":"5"}';if(path.includes('applicable-'))return'{"name":"Sales team","commission_policy":2,"applicable_staff":[7,8]}';return method==='POST'||method==='PUT'?'{"name":"Commission policy","from_date":"2026-01-01","commission_policy_type":"percentage","percent_enjoyed":"10"}':''}
function example(method:string,path:string){const data=body(method,path);return`curl -X ${method} "https://yoursite.com${path.replace(':id','42')}" \
  -H "authtoken: YOUR_API_TOKEN"${data?` \\\n  -H "Content-Type: application/json" \\\n  -d '${data}'`:''}`}
function Code({children}:{children:string}){return <pre className="astro-code catppuccin-mocha" style={{backgroundColor:'#1e1e2e',color:'#cdd6f4',overflowX:'auto'}}><code>{children}</code><CopyButton hidden={false}/></pre>}
export default function CommissionSection(){return <section id="api-sales-commission"><h2>Sales Commission</h2><article><h1>Sales Commission endpoints</h1><div className="row pre-post"><div className="col-md-7 no-float"><div className="endpoint-desc"><p>Manage calculated commissions, policies, staff and client applicability, hierarchies, sales-admin groups, receipts, reports and recalculation through API v3.</p><p>The Commission module must be active. Authenticate with <code>authtoken</code> and grant the matching Sales Commission GET, POST, PUT or DELETE capability.</p></div><div className="table-responsive-wrapper"><table className="table table-hover"><thead><tr><th>Method</th><th>Endpoint</th><th>Operation</th></tr></thead><tbody>{commissionEndpoints.map(([m,t,p])=><tr key={`${m}-${p}`}><td>{m}</td><td><code>{p}</code></td><td>{t}</td></tr>)}</tbody></table></div></div><div className="col-md-4 section-example no-float"><Code>{example('GET','/api/commission')}</Code></div></div></article>{commissionEndpoints.map(([m,t,p,d])=><article id={commissionAnchor(m,t)} key={`${m}-${p}`}><h1>{t}</h1><div className="row pre-post"><div className="col-md-7 no-float"><pre className="full-pre"><span className={`typ typ-${m.toLowerCase()}`}>{m}</span><span className="url">{p}</span></pre><div className="endpoint-desc"><p>{d}</p></div></div><div className="col-md-4 section-example no-float"><Code>{example(m,p)}</Code></div></div></article>)}</section>}
