import React from 'react'
import CopyButton from './CopyButton.tsx'
export const myshopifyEndpoints=[
['GET','Discover endpoints','/api/myshopify','Return endpoints and whether Shopify credentials are configured.'],
['GET','List products','/api/myshopify/products','List locally imported Shopify products.'],['GET','Get product','/api/myshopify/products/:id','Get an imported product.'],
['GET','List customers','/api/myshopify/customers','List locally imported Shopify customers.'],['GET','Get customer','/api/myshopify/customers/:id','Get an imported customer.'],
['GET','List orders','/api/myshopify/orders','List locally imported Shopify orders.'],['GET','Get order','/api/myshopify/orders/:id','Get an imported order and its stored line items.'],
['GET','List categories','/api/myshopify/categories','List imported Shopify collections.'],['GET','Get category','/api/myshopify/categories/:id','Get an imported category.'],
['GET','List discounts','/api/myshopify/discounts','List imported Shopify discounts.'],['GET','Get discount','/api/myshopify/discounts/:id','Get an imported discount.'],
['GET','List identity maps','/api/myshopify/maps/:type','List products, customers, categories or orders identity mappings.'],
['GET','List sync logs','/api/myshopify/logs','List synchronization logs with direction, entity_type and status filters.'],['GET','Get sync log','/api/myshopify/logs/:id','Get one synchronization log.'],
['POST','Run reconciliation','/api/myshopify/sync','Pull changed Shopify records and push mapped Perfex categories.'],
['POST','Register webhooks','/api/myshopify/webhooks/register','Register all required event topics with Shopify.'],
['POST','Push customer','/api/myshopify/push/customer/:id','Push a Perfex customer to Shopify.'],['POST','Push item','/api/myshopify/push/item/:id','Push a Perfex item and mapped stock to Shopify.'],
['POST','Push inventory','/api/myshopify/push/inventory','Push all mapped Warehouse inventory levels.'],['POST','Push categories','/api/myshopify/push/categories','Push Perfex item groups to Shopify collections.'],
] as const
export const myshopifyAnchor=(m:string,t:string)=>`api-myshopify-${m.toLowerCase()}-${t.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}`
function example(m:string,p:string){return`curl -X ${m} "https://yoursite.com${p.replace(':type','products').replace(':id','42')}" \\\n  -H "authtoken: YOUR_API_TOKEN"`}
function Code({children}:{children:string}){return <pre className="astro-code catppuccin-mocha" style={{backgroundColor:'#1e1e2e',color:'#cdd6f4',overflowX:'auto'}}><code>{children}</code><CopyButton hidden={false}/></pre>}
export default function MyshopifySection(){return <section id="api-myshopify"><h2>MyShopify</h2><article><h1>MyShopify endpoints</h1><div className="row pre-post"><div className="col-md-7 no-float"><div className="endpoint-desc"><p>Inspect imported Shopify data and identity mappings, audit synchronization logs, run reconciliation, register webhooks, and push customers, items, inventory and categories.</p><p>The MyShopify module and Shopify credentials must be active. Read operations require MyShopify GET permission; synchronization actions require POST permission.</p><p>Inbound Shopify webhooks continue to use the signed public <code>/myshopify/webhook</code> receiver; they do not use an API token.</p></div><div className="table-responsive-wrapper"><table className="table table-hover"><thead><tr><th>Method</th><th>Endpoint</th><th>Operation</th></tr></thead><tbody>{myshopifyEndpoints.map(([m,t,p])=><tr key={`${m}-${p}`}><td>{m}</td><td><code>{p}</code></td><td>{t}</td></tr>)}</tbody></table></div></div><div className="col-md-4 section-example no-float"><Code>{example('GET','/api/myshopify')}</Code></div></div></article>{myshopifyEndpoints.map(([m,t,p,d])=><article id={myshopifyAnchor(m,t)} key={`${m}-${p}`}><h1>{t}</h1><div className="row pre-post"><div className="col-md-7 no-float"><pre className="full-pre"><span className={`typ typ-${m.toLowerCase()}`}>{m}</span><span className="url">{p}</span></pre><div className="endpoint-desc"><p>{d}</p></div></div><div className="col-md-4 section-example no-float"><Code>{example(m,p)}</Code></div></div></article>)}</section>}
