import React from 'react'
import CopyButton from './CopyButton.tsx'
export const purchaseEndpoints = [
["GET", "Discover endpoints", "/api/purchase", "Return the Purchase Management endpoint catalog."],
["GET", "List Vendors", "/api/purchase/vendors", "List vendors records with pagination."],
["POST", "Create Vendors", "/api/purchase/vendors", "Create a vendors record using the native Purchase module payload."],
["GET", "Get Vendors", "/api/purchase/vendors/:id", "Retrieve one vendors record and available document details."],
["PUT", "Update Vendors", "/api/purchase/vendors/:id", "Update a vendors record."],
["DELETE", "Delete Vendors", "/api/purchase/vendors/:id", "Delete a vendors record when supported by module rules."],
["GET", "List Requests", "/api/purchase/requests", "List requests records with pagination."],
["POST", "Create Requests", "/api/purchase/requests", "Create a requests record using the native Purchase module payload."],
["GET", "Get Requests", "/api/purchase/requests/:id", "Retrieve one requests record and available document details."],
["PUT", "Update Requests", "/api/purchase/requests/:id", "Update a requests record."],
["DELETE", "Delete Requests", "/api/purchase/requests/:id", "Delete a requests record when supported by module rules."],
["GET", "List Quotations", "/api/purchase/quotations", "List quotations records with pagination."],
["POST", "Create Quotations", "/api/purchase/quotations", "Create a quotations record using the native Purchase module payload."],
["GET", "Get Quotations", "/api/purchase/quotations/:id", "Retrieve one quotations record and available document details."],
["PUT", "Update Quotations", "/api/purchase/quotations/:id", "Update a quotations record."],
["DELETE", "Delete Quotations", "/api/purchase/quotations/:id", "Delete a quotations record when supported by module rules."],
["GET", "List Orders", "/api/purchase/orders", "List orders records with pagination."],
["POST", "Create Orders", "/api/purchase/orders", "Create a orders record using the native Purchase module payload."],
["GET", "Get Orders", "/api/purchase/orders/:id", "Retrieve one orders record and available document details."],
["PUT", "Update Orders", "/api/purchase/orders/:id", "Update a orders record."],
["DELETE", "Delete Orders", "/api/purchase/orders/:id", "Delete a orders record when supported by module rules."],
["GET", "List Contracts", "/api/purchase/contracts", "List contracts records with pagination."],
["POST", "Create Contracts", "/api/purchase/contracts", "Create a contracts record using the native Purchase module payload."],
["GET", "Get Contracts", "/api/purchase/contracts/:id", "Retrieve one contracts record and available document details."],
["PUT", "Update Contracts", "/api/purchase/contracts/:id", "Update a contracts record."],
["DELETE", "Delete Contracts", "/api/purchase/contracts/:id", "Delete a contracts record when supported by module rules."],
["GET", "List Invoices", "/api/purchase/invoices", "List invoices records with pagination."],
["POST", "Create Invoices", "/api/purchase/invoices", "Create a invoices record using the native Purchase module payload."],
["GET", "Get Invoices", "/api/purchase/invoices/:id", "Retrieve one invoices record and available document details."],
["PUT", "Update Invoices", "/api/purchase/invoices/:id", "Update a invoices record."],
["DELETE", "Delete Invoices", "/api/purchase/invoices/:id", "Delete a invoices record when supported by module rules."],
["GET", "List Debit Notes", "/api/purchase/debit-notes", "List debit notes records with pagination."],
["POST", "Create Debit Notes", "/api/purchase/debit-notes", "Create a debit notes record using the native Purchase module payload."],
["GET", "Get Debit Notes", "/api/purchase/debit-notes/:id", "Retrieve one debit notes record and available document details."],
["PUT", "Update Debit Notes", "/api/purchase/debit-notes/:id", "Update a debit notes record."],
["DELETE", "Delete Debit Notes", "/api/purchase/debit-notes/:id", "Delete a debit notes record when supported by module rules."],
["GET", "List Order Returns", "/api/purchase/order-returns", "List order returns records with pagination."],
["POST", "Create Order Returns", "/api/purchase/order-returns", "Create a order returns record using the native Purchase module payload."],
["GET", "Get Order Returns", "/api/purchase/order-returns/:id", "Retrieve one order returns record and available document details."],
["PUT", "Update Order Returns", "/api/purchase/order-returns/:id", "Update a order returns record."],
["DELETE", "Delete Order Returns", "/api/purchase/order-returns/:id", "Delete a order returns record when supported by module rules."],
["GET", "List Vendor Categories", "/api/purchase/vendor-categories", "List vendor categories records with pagination."],
["POST", "Create Vendor Categories", "/api/purchase/vendor-categories", "Create a vendor categories record using the native Purchase module payload."],
["GET", "Get Vendor Categories", "/api/purchase/vendor-categories/:id", "Retrieve one vendor categories record and available document details."],
["PUT", "Update Vendor Categories", "/api/purchase/vendor-categories/:id", "Update a vendor categories record."],
["DELETE", "Delete Vendor Categories", "/api/purchase/vendor-categories/:id", "Delete a vendor categories record when supported by module rules."],
["GET", "List Units", "/api/purchase/units", "List units records with pagination."],
["POST", "Create Units", "/api/purchase/units", "Create a units record using the native Purchase module payload."],
["GET", "Get Units", "/api/purchase/units/:id", "Retrieve one units record and available document details."],
["PUT", "Update Units", "/api/purchase/units/:id", "Update a units record."],
["DELETE", "Delete Units", "/api/purchase/units/:id", "Delete a units record when supported by module rules."],
["GET", "List Commodity Groups", "/api/purchase/commodity-groups", "List commodity groups records with pagination."],
["POST", "Create Commodity Groups", "/api/purchase/commodity-groups", "Create a commodity groups record using the native Purchase module payload."],
["GET", "Get Commodity Groups", "/api/purchase/commodity-groups/:id", "Retrieve one commodity groups record and available document details."],
["PUT", "Update Commodity Groups", "/api/purchase/commodity-groups/:id", "Update a commodity groups record."],
["DELETE", "Delete Commodity Groups", "/api/purchase/commodity-groups/:id", "Delete a commodity groups record when supported by module rules."],
["GET", "List Sub Groups", "/api/purchase/sub-groups", "List sub groups records with pagination."],
["POST", "Create Sub Groups", "/api/purchase/sub-groups", "Create a sub groups record using the native Purchase module payload."],
["GET", "Get Sub Groups", "/api/purchase/sub-groups/:id", "Retrieve one sub groups record and available document details."],
["PUT", "Update Sub Groups", "/api/purchase/sub-groups/:id", "Update a sub groups record."],
["DELETE", "Delete Sub Groups", "/api/purchase/sub-groups/:id", "Delete a sub groups record when supported by module rules."],
["GET", "List Approval Settings", "/api/purchase/approval-settings", "List approval settings records with pagination."],
["POST", "Create Approval Settings", "/api/purchase/approval-settings", "Create a approval settings record using the native Purchase module payload."],
["GET", "Get Approval Settings", "/api/purchase/approval-settings/:id", "Retrieve one approval settings record and available document details."],
["PUT", "Update Approval Settings", "/api/purchase/approval-settings/:id", "Update a approval settings record."],
["DELETE", "Delete Approval Settings", "/api/purchase/approval-settings/:id", "Delete a approval settings record when supported by module rules."],
["GET", "List Vendor Items", "/api/purchase/vendor-items", "List vendor items records with pagination."],
["POST", "Create Vendor Items", "/api/purchase/vendor-items", "Create a vendor items record using the native Purchase module payload."],
["GET", "Get Vendor Items", "/api/purchase/vendor-items/:id", "Retrieve one vendor items record and available document details."],
["PUT", "Update Vendor Items", "/api/purchase/vendor-items/:id", "Update a vendor items record."],
["DELETE", "Delete Vendor Items", "/api/purchase/vendor-items/:id", "Delete a vendor items record when supported by module rules."],
["PUT", "Change Requests Status", "/api/purchase/requests/:id/status", "Change the requests workflow status."],
["GET", "Get Requests PDF", "/api/purchase/requests/:id/pdf", "Return the requests PDF as Base64."],
["PUT", "Change Quotations Status", "/api/purchase/quotations/:id/status", "Change the quotations workflow status."],
["GET", "Get Quotations PDF", "/api/purchase/quotations/:id/pdf", "Return the quotations PDF as Base64."],
["PUT", "Change Orders Status", "/api/purchase/orders/:id/status", "Change the orders workflow status."],
["GET", "Get Orders PDF", "/api/purchase/orders/:id/pdf", "Return the orders PDF as Base64."],
["GET", "List Orders Payments", "/api/purchase/orders/:id/payments", "List payments recorded against the orders record."],
["POST", "Add Orders Payment", "/api/purchase/orders/:id/payments", "Add a payment against the orders record."],
["GET", "List Invoices Payments", "/api/purchase/invoices/:id/payments", "List payments recorded against the invoices record."],
["POST", "Add Invoices Payment", "/api/purchase/invoices/:id/payments", "Add a payment against the invoices record."],
["GET", "Get Vendor Statement", "/api/purchase/vendors/:id/statement", "Return a vendor statement using optional from and to dates."]
] as const
export const purchaseAnchor=(m:string,t:string)=>`api-purchase-${m.toLowerCase()}-${t.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}`
function example(m:string,p:string){const body=(m==='POST'||m==='PUT')?' \\\n  -H "Content-Type: application/json" \\\n  -d '{"status":2}'':'';return`curl -X ${m} "https://yoursite.com${p.replace(':id','42')}" \\\n  -H "authtoken: YOUR_API_TOKEN"${body}`}
function Code({children}:{children:string}){return <pre className="astro-code catppuccin-mocha" style={{backgroundColor:'#1e1e2e',color:'#cdd6f4',overflowX:'auto'}}><code>{children}</code><CopyButton hidden={false}/></pre>}
export default function PurchaseSection(){return <section id="api-purchase-management"><h2>Purchase Management</h2><article><h1>Purchase Management endpoints</h1><div className="row pre-post"><div className="col-md-7 no-float"><div className="endpoint-desc"><p>Manage vendors, requests, quotations, purchase orders, contracts, invoices, debit notes, returns, settings, items, payments and vendor statements.</p><p>The Purchase module must be active. Authenticate using <code>authtoken</code> and grant the matching Purchase Management method permission.</p><p>Document create/update payloads use the native module structure and support <code>newitems</code> for line items.</p></div><div className="table-responsive-wrapper"><table className="table table-hover"><thead><tr><th>Method</th><th>Endpoint</th><th>Operation</th></tr></thead><tbody>{purchaseEndpoints.map(([m,t,p])=><tr key={`${m}-${p}`}><td>{m}</td><td><code>{p}</code></td><td>{t}</td></tr>)}</tbody></table></div></div><div className="col-md-4 section-example no-float"><Code>{example('GET','/api/purchase')}</Code></div></div></article>{purchaseEndpoints.map(([m,t,p,d])=><article id={purchaseAnchor(m,t)} key={`${m}-${p}`}><h1>{t}</h1><div className="row pre-post"><div className="col-md-7 no-float"><pre className="full-pre"><span className={`typ typ-${m.toLowerCase()}`}>{m}</span><span className="url">{p}</span></pre><p>{d}</p></div><div className="col-md-4 section-example no-float"><Code>{example(m,p)}</Code></div></div></article>)}</section>}
